-- MySQL Script generated by MySQL Workbench
-- Mon Apr 12 21:27:02 2021
-- Model: New Model  Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gradebook
-- -----------------------------------------------------
-- Gradebook schema for IS668 project

-- -----------------------------------------------------
-- Schema gradebook
--
-- Gradebook schema for IS668 project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS gradebook DEFAULT CHARACTER SET utf8 ;
USE gradebook ;

-- -----------------------------------------------------
-- Table  student 
-- -----------------------------------------------------
DROP TABLE IF EXISTS  student ;

CREATE TABLE IF NOT EXISTS student (
  student_ID INT NOT NULL COMMENT 'Artificial primary key.',
  first_name VARCHAR(45) NOT NULL COMMENT 'The first name of the student.',
  last_name VARCHAR(45) NOT NULL COMMENT 'The last name of the student.',
  email_address VARCHAR(45) NULL COMMENT 'The email address of the student.',
  major VARCHAR(45) NULL COMMENT 'The school major of the student.',
 PRIMARY KEY ( student_ID ))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  school_class 
-- -----------------------------------------------------
DROP TABLE IF EXISTS school_class ;

CREATE TABLE IF NOT EXISTS school_class (
  class_ID INT NOT NULL,
  class_name VARCHAR(45) NOT NULL COMMENT 'The name of the school class.',
  department VARCHAR(45) NULL COMMENT 'The department the class belongs in.',
 PRIMARY KEY ( class_ID ))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  school_class_offering 
-- -----------------------------------------------------
DROP TABLE IF EXISTS school_class_offering ;

CREATE TABLE IF NOT EXISTS  school_class_offering (
  class_ID INT NOT NULL COMMENT 'Foreign key from schoolClass table.',
  semester VARCHAR(45) NOT NULL COMMENT 'The semester the class took place in.',
  class_year INT NOT NULL COMMENT 'The year the class took place in.',
  class_offering_ID INT NOT NULL COMMENT 'Artificial primary key.',
 PRIMARY KEY (class_offering_ID),
 CONSTRAINT class_ID_constraint
  FOREIGN KEY (class_ID)
  REFERENCES school_class (class_ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table  student_school_class_offering 
-- -----------------------------------------------------
DROP TABLE IF EXISTS  student_school_class_offering;

CREATE TABLE IF NOT EXISTS  student_school_class_offering (
  student_ID INT NOT NULL COMMENT 'Foreign key from student table. Composite primary key.',
  class_offering_ID INT NOT NULL COMMENT 'Foreign key from schoolClassOffering table. Composite primary key.',
 PRIMARY KEY ( class_offering_ID , student_ID ),
 CONSTRAINT student_ID_constraint
  FOREIGN KEY(student_ID)
  REFERENCES student(student_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
 CONSTRAINT class_offering_ID_constraint
  FOREIGN KEY(class_offering_ID)
  REFERENCES school_class_offering(class_offering_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table  assignment 
-- -----------------------------------------------------
DROP TABLE IF EXISTS assignment;

CREATE TABLE IF NOT EXISTS assignment (
  assignment_ID INT NOT NULL COMMENT 'Artificial primary key.',
  assignment_name VARCHAR(45) NULL COMMENT 'The name of the assignment.',
  class_offering_ID INT NOT NULL COMMENT 'Foreign key from schoolClass table.',
 PRIMARY KEY (assignment_ID),
 CONSTRAINT class_offering_ID_assignment_constraint
  FOREIGN KEY(class_offering_ID)
  REFERENCES school_class_offering(class_offering_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table  grade 
-- -----------------------------------------------------
DROP TABLE IF EXISTS  grade ;

CREATE TABLE IF NOT EXISTS  grade (
  grade_ID INT NOT NULL,
  assignment_ID INT NOT NULL COMMENT 'Foreign key from assignment table. Part of composite primary key.',
  student_ID INT NOT NULL COMMENT 'Foreign key from student table. Part of composite primary key.',
  grade FLOAT NULL COMMENT 'Stores a student grade for an assignment',
 PRIMARY KEY (grade_ID),
 CONSTRAINT assignment_ID_grade_constraint
  FOREIGN KEY(assignment_ID)
  REFERENCES  assignment(assignment_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
 CONSTRAINT student_ID_grade_constraint
  FOREIGN KEY(student_ID)
  REFERENCES student(student_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
