-- MySQL Script generated by MySQL Workbench
-- Mon Apr 12 21:27:02 2021
-- Model: New Model  Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gradebook
-- -----------------------------------------------------
-- Gradebook schema for IS668 project

-- -----------------------------------------------------
-- Schema gradebook
--
-- Gradebook schema for IS668 project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS gradebook DEFAULT CHARACTER SET utf8 ;
USE gradebook ;

-- -----------------------------------------------------
-- Table  student 
-- -----------------------------------------------------
DROP TABLE IF EXISTS  student ;

CREATE TABLE IF NOT EXISTS student (
  studentID INT NOT NULL COMMENT 'Artificial primary key.',
  firstName VARCHAR(45) NOT NULL COMMENT 'The first name of the student.',
  lastName VARCHAR(45) NOT NULL COMMENT 'The last name of the student.',
  emailAddress VARCHAR(45) NULL COMMENT 'The email address of the student.',
  major VARCHAR(45) NULL COMMENT 'The school major of the student.',
 PRIMARY KEY ( studentID ))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  schoolClass 
-- -----------------------------------------------------
DROP TABLE IF EXISTS schoolClass ;

CREATE TABLE IF NOT EXISTS schoolClass (
  classID INT NOT NULL,
  className VARCHAR(45) NOT NULL COMMENT 'The name of the school class.',
  department VARCHAR(45) NULL COMMENT 'The department the class belongs in.',
 PRIMARY KEY ( classID ))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table  schoolClassOffering 
-- -----------------------------------------------------
DROP TABLE IF EXISTS schoolClassOffering ;

CREATE TABLE IF NOT EXISTS  schoolClassOffering (
  classID INT NOT NULL COMMENT 'Foreign key from schoolClass table.',
  semester VARCHAR(45) NOT NULL COMMENT 'The semester the class took place in.',
  year INT NOT NULL COMMENT 'The year the class took place in.',
  classOfferingID INT NOT NULL COMMENT 'Artificial primary key.',
 PRIMARY KEY (classOfferingID),
 CONSTRAINT classIDConstraint
  FOREIGN KEY (classID)
  REFERENCES schoolClass (classID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table  studentSchoolClassOffering 
-- -----------------------------------------------------
DROP TABLE IF EXISTS  studentSchoolClassOffering;

CREATE TABLE IF NOT EXISTS  studentSchoolClassOffering (
  studentID INT NOT NULL COMMENT 'Foreign key from student table. Composite primary key.',
  classOfferingID INT NOT NULL COMMENT 'Foreign key from schoolClassOffering table. Composite primary key.',
 PRIMARY KEY ( classOfferingID , studentID ),
 CONSTRAINT studentIDConstraint
  FOREIGN KEY(studentID)
  REFERENCES student(studentID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
 CONSTRAINT classOfferingIDConstraint
  FOREIGN KEY(classOfferingID)
  REFERENCES schoolClassOffering(classOfferingID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table  assignment 
-- -----------------------------------------------------
DROP TABLE IF EXISTS assignment;

CREATE TABLE IF NOT EXISTS assignment (
  assignmentID INT NOT NULL COMMENT 'Artificial primary key.',
  assignmentName VARCHAR(45) NULL COMMENT 'The name of the assignment.',
  classOfferingID INT NOT NULL COMMENT 'Foreign key from schoolClass table.',
 PRIMARY KEY (assignmentID),
 CONSTRAINT classOfferingIDAssignmentConstraint
  FOREIGN KEY(classOfferingID)
  REFERENCES schoolClassOffering(classOfferingID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table  grade 
-- -----------------------------------------------------
DROP TABLE IF EXISTS  grade ;

CREATE TABLE IF NOT EXISTS  grade (
  assignmentID INT NOT NULL COMMENT 'Foreign key from assignment table. Part of composite primary key.',
  studentID INT NOT NULL COMMENT 'Foreign key from student table. Part of composite primary key.',
  grade FLOAT NULL COMMENT 'Store\'s a student\'s grade for an assignment',
 PRIMARY KEY ( assignmentID , studentID ),
 CONSTRAINT assignmentIDGradeConstraint
  FOREIGN KEY(assignmentID)
  REFERENCES  assignment(assignmentID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
 CONSTRAINT studentIDGradeConstraint
  FOREIGN KEY(studentID)
  REFERENCES student(studentID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
